"""Session 238: insert feininger_crystalline_prism_pass + paint_split_toning_pass into stroke_engine.py."""
import sys, os
sys.stdout.reconfigure(encoding='utf-8')
os.chdir(os.path.dirname(os.path.abspath(__file__)))

FEININGER_PASS = (
    "\n"
    "    def feininger_crystalline_prism_pass(\n"
    "        self,\n"
    "        facet_sigma:   float = 8.0,\n"
    "        prism_cycles:  float = 3.0,\n"
    "        chroma_tilt:   float = 0.10,\n"
    "        lum_facet:     float = 0.06,\n"
    "        opacity:       float = 0.72,\n"
    "    ) -> None:\n"
    "        r\"\"\"\n"
    "        Feininger Crystalline Prism -- session 238: ONE HUNDRED AND FORTY-NINTH distinct mode.\n"
    "\n"
    "        Implements Lyonel Feininger (1871-1956) Cubist-Expressionist crystalline\n"
    "        aesthetic.  Feininger organised his canvases as interlocking angular planes\n"
    "        of subtly differentiated atmospheric colour, each planar zone catching light\n"
    "        from a slightly different directional angle -- the structural logic of a\n"
    "        crystal face illuminated by directional light.\n"
    "\n"
    "        TWO-STAGE CRYSTALLINE FACET SIMULATION unified by gradient direction angle:\n"
    "\n"
    "        Stage 1 COHERENT ANGLE MAP via circular Gaussian averaging:\n"
    "        sx = sobel(lum, axis=1); sy = sobel(lum, axis=0);\n"
    "        angle = atan2(sy, sx) in [-pi, pi].\n"
    "        Circular averaging (correct for angle arithmetic -- not affected by\n"
    "        the 2*pi wraparound discontinuity):\n"
    "        z_cos = gaussian(cos(angle), facet_sigma);\n"
    "        z_sin = gaussian(sin(angle), facet_sigma);\n"
    "        coherent_angle = atan2(z_sin, z_cos).\n"
    "        FIRST pass in project to use spatial gradient DIRECTION (atan2) as its\n"
    "        primary variable -- all prior Sobel-based passes (e.g. rouault_stained_glass)\n"
    "        use gradient MAGNITUDE only.  FIRST use of circular/angular Gaussian\n"
    "        blurring via complex-exponential decomposition.\n"
    "\n"
    "        Stage 2 PRISMATIC WARM/COOL CHROMATIC MAPPING:\n"
    "        warm_cool = cos(coherent_angle * prism_cycles) in [-1, 1].\n"
    "        lum_mod   = sin(coherent_angle * prism_cycles + pi/6) * lum_facet.\n"
    "        Channel adjustments:\n"
    "        R += warm_cool * ct * 0.78 + lum_mod;\n"
    "        G += warm_cool * ct * 0.28 + lum_mod * 0.80;\n"
    "        B -= warm_cool * ct * 0.92 - lum_mod * 0.60.\n"
    "        Positive warm_cool: R+, G+slightly, B- (amber/warm crystal face).\n"
    "        Negative warm_cool: R-, G-slightly, B+ (cobalt/cool crystal face).\n"
    "        FIRST cyclic periodic warm/cool mapping governed by local gradient\n"
    "        DIRECTION -- prior periodic passes (e.g. kupka_orphic_fugue) derive\n"
    "        oscillation from spatial POSITION (radial distance from centroid),\n"
    "        not from local gradient orientation angle.\n"
    "\n"
    "        NOVEL vs. existing passes:\n"
    "        (a) CIRCULAR ANGLE AVERAGING via cos/sin decomposition -- first\n"
    "            directional spatial average; prior Sobel passes use only magnitude.\n"
    "        (b) GRADIENT DIRECTION (atan2) as primary mapping variable, not magnitude.\n"
    "        (c) CYCLIC DIRECTION-ANGLE chromatic modulation -- first pass where\n"
    "            warm/cool oscillation is governed by local gradient orientation.\n"
    "\n"
    "        facet_sigma  : Gaussian blur radius for coherent angle region formation.\n"
    "        prism_cycles : Number of warm/cool oscillation cycles per 2*pi angle sweep.\n"
    "        chroma_tilt  : Maximum chromatic deviation in warm or cool direction [0, 0.20].\n"
    "        lum_facet    : Luminance modulation amplitude across facet planes [0, 0.12].\n"
    "        opacity      : Final composite opacity.\n"
    "        \"\"\"\n"
    "        import numpy as _np\n"
    "        from scipy.ndimage import sobel as _sobel, gaussian_filter as _gf\n"
    "\n"
    "        print(\"    Feininger Crystalline Prism pass (session 238: 149th mode)...\")\n"
    "\n"
    "        surface = self.canvas.surface\n"
    "        orig = _np.frombuffer(surface.get_data(), dtype=_np.uint8).reshape(\n"
    "            (self.canvas.h, self.canvas.w, 4)).copy()\n"
    "\n"
    "        b0 = orig[:, :, 0].astype(_np.float32) / 255.0\n"
    "        g0 = orig[:, :, 1].astype(_np.float32) / 255.0\n"
    "        r0 = orig[:, :, 2].astype(_np.float32) / 255.0\n"
    "\n"
    "        lum = (0.299 * r0 + 0.587 * g0 + 0.114 * b0).astype(_np.float32)\n"
    "\n"
    "        # Stage 1: Coherent angle map via circular Gaussian averaging\n"
    "        sx = _sobel(lum, axis=1).astype(_np.float32)\n"
    "        sy = _sobel(lum, axis=0).astype(_np.float32)\n"
    "        angle = _np.arctan2(sy, sx).astype(_np.float32)\n"
    "\n"
    "        sigma = float(facet_sigma)\n"
    "        z_cos = _gf(_np.cos(angle).astype(_np.float32), sigma)\n"
    "        z_sin = _gf(_np.sin(angle).astype(_np.float32), sigma)\n"
    "        coherent_angle = _np.arctan2(z_sin, z_cos).astype(_np.float32)\n"
    "\n"
    "        # Stage 2: Prismatic warm/cool chromatic mapping\n"
    "        pc = float(prism_cycles)\n"
    "        warm_cool = _np.cos(coherent_angle * pc).astype(_np.float32)\n"
    "        lum_mod   = (_np.sin(coherent_angle * pc + _np.pi / 6.0)\n"
    "                     * float(lum_facet)).astype(_np.float32)\n"
    "\n"
    "        ct = float(chroma_tilt)\n"
    "        r1 = _np.clip(r0 + warm_cool * ct * 0.78 + lum_mod, 0.0, 1.0)\n"
    "        g1 = _np.clip(g0 + warm_cool * ct * 0.28 + lum_mod * 0.80, 0.0, 1.0)\n"
    "        b1 = _np.clip(b0 - warm_cool * ct * 0.92 + lum_mod * 0.60, 0.0, 1.0)\n"
    "\n"
    "        op = float(opacity)\n"
    "        new_r = r0 * (1.0 - op) + r1 * op\n"
    "        new_g = g0 * (1.0 - op) + g1 * op\n"
    "        new_b = b0 * (1.0 - op) + b1 * op\n"
    "\n"
    "        buf = orig.copy()\n"
    "        buf[:, :, 2] = _np.clip(new_r * 255, 0, 255).astype(_np.uint8)\n"
    "        buf[:, :, 1] = _np.clip(new_g * 255, 0, 255).astype(_np.uint8)\n"
    "        buf[:, :, 0] = _np.clip(new_b * 255, 0, 255).astype(_np.uint8)\n"
    "        buf[:, :, 3] = orig[:, :, 3]\n"
    "        surface.get_data()[:] = buf.tobytes()\n"
    "        surface.mark_dirty()\n"
    "\n"
    "        n_warm = int((warm_cool > 0.5).sum())\n"
    "        n_cool = int((warm_cool < -0.5).sum())\n"
    "        print(f\"    Feininger Crystalline Prism complete \"\n"
    "              f\"(warm_px={n_warm} cool_px={n_cool})\")\n"
)

SPLIT_TONING_PASS = (
    "\n"
    "    def paint_split_toning_pass(\n"
    "        self,\n"
    "        shadow_cool:      float = 0.065,\n"
    "        highlight_warm:   float = 0.055,\n"
    "        shadow_pivot:     float = 0.30,\n"
    "        highlight_pivot:  float = 0.72,\n"
    "        transition_width: float = 0.18,\n"
    "        opacity:          float = 0.52,\n"
    "    ) -> None:\n"
    "        r\"\"\"\n"
    "        Paint Split Toning -- session 238 improvement.\n"
    "\n"
    "        Split toning is a photographic darkroom technique in which shadow and\n"
    "        highlight regions receive distinct, opposing colour tints while midtones\n"
    "        remain near-neutral.  Classic split toning pushes shadows toward cool\n"
    "        blue-teal and highlights toward warm amber-gold, reinforcing the natural\n"
    "        temperature contrast between ambient (cool sky fill) and direct (warm sun)\n"
    "        light sources.\n"
    "\n"
    "        TWO-STAGE SPLIT TONING:\n"
    "\n"
    "        Stage 1 LUMINANCE ZONE GATES with smooth linear transitions:\n"
    "        shadow_gate    = clip((shadow_pivot - lum) / transition_width, 0, 1).\n"
    "        highlight_gate = clip((lum - highlight_pivot) / transition_width, 0, 1).\n"
    "        Both gates ramp from 0 to 1 over a transition_width luminance band.\n"
    "        Midtone region (luminances between the two pivots) receives zero tinting.\n"
    "\n"
    "        Stage 2 OPPOSING DUAL-ZONE TINTING:\n"
    "        Shadow (cool): R -= shadow_gate * shadow_cool * 0.50;\n"
    "                       G -= shadow_gate * shadow_cool * 0.15;\n"
    "                       B += shadow_gate * shadow_cool * 0.90.\n"
    "        Highlight (warm): R += highlight_gate * highlight_warm * 0.88;\n"
    "                          G += highlight_gate * highlight_warm * 0.48;\n"
    "                          B -= highlight_gate * highlight_warm * 0.65.\n"
    "        Both adjustments are summed before opacity composite.\n"
    "\n"
    "        NOVEL vs. existing passes:\n"
    "        (a) SIMULTANEOUS OPPOSING DUAL-ZONE TINTING: shadows driven cool (B+,R-)\n"
    "            and highlights driven warm (R+,B-) in a single pass -- no prior pass\n"
    "            applies two opposing colour shifts to two distinct luminance zones\n"
    "            simultaneously.\n"
    "        (b) THREE-ZONE LUMINANCE SEGMENTATION (shadow/midtone/highlight) with\n"
    "            independent smooth linear gates -- prior lum-gated passes (scumble,\n"
    "            varnish, granulation) operate on a single zone or one-sided ramp.\n"
    "\n"
    "        shadow_cool      : Max cool tint in dark zones [0, 0.15].\n"
    "        highlight_warm   : Max warm tint in bright zones [0, 0.12].\n"
    "        shadow_pivot     : Luminance below which shadow tint is at full strength.\n"
    "        highlight_pivot  : Luminance above which highlight tint begins to ramp.\n"
    "        transition_width : Luminance width of each tint ramp zone.\n"
    "        opacity          : Final composite opacity.\n"
    "        \"\"\"\n"
    "        import numpy as _np\n"
    "\n"
    "        print(\"    Paint Split Toning pass (session 238 improvement)...\")\n"
    "\n"
    "        surface = self.canvas.surface\n"
    "        orig = _np.frombuffer(surface.get_data(), dtype=_np.uint8).reshape(\n"
    "            (self.canvas.h, self.canvas.w, 4)).copy()\n"
    "\n"
    "        b0 = orig[:, :, 0].astype(_np.float32) / 255.0\n"
    "        g0 = orig[:, :, 1].astype(_np.float32) / 255.0\n"
    "        r0 = orig[:, :, 2].astype(_np.float32) / 255.0\n"
    "\n"
    "        lum = (0.299 * r0 + 0.587 * g0 + 0.114 * b0).astype(_np.float32)\n"
    "\n"
    "        # Stage 1: Luminance zone gates\n"
    "        tw = float(transition_width)\n"
    "        sp = float(shadow_pivot)\n"
    "        hp = float(highlight_pivot)\n"
    "        shadow_gate    = _np.clip((sp - lum) / (tw + 1e-7), 0.0, 1.0)\n"
    "        highlight_gate = _np.clip((lum - hp) / (tw + 1e-7), 0.0, 1.0)\n"
    "\n"
    "        # Stage 2: Opposing dual-zone tinting\n"
    "        sc = float(shadow_cool)\n"
    "        hw = float(highlight_warm)\n"
    "        r_adj = -shadow_gate * sc * 0.50 + highlight_gate * hw * 0.88\n"
    "        g_adj = -shadow_gate * sc * 0.15 + highlight_gate * hw * 0.48\n"
    "        b_adj = +shadow_gate * sc * 0.90 - highlight_gate * hw * 0.65\n"
    "\n"
    "        r1 = _np.clip(r0 + r_adj, 0.0, 1.0)\n"
    "        g1 = _np.clip(g0 + g_adj, 0.0, 1.0)\n"
    "        b1 = _np.clip(b0 + b_adj, 0.0, 1.0)\n"
    "\n"
    "        op = float(opacity)\n"
    "        new_r = r0 * (1.0 - op) + r1 * op\n"
    "        new_g = g0 * (1.0 - op) + g1 * op\n"
    "        new_b = b0 * (1.0 - op) + b1 * op\n"
    "\n"
    "        buf = orig.copy()\n"
    "        buf[:, :, 2] = _np.clip(new_r * 255, 0, 255).astype(_np.uint8)\n"
    "        buf[:, :, 1] = _np.clip(new_g * 255, 0, 255).astype(_np.uint8)\n"
    "        buf[:, :, 0] = _np.clip(new_b * 255, 0, 255).astype(_np.uint8)\n"
    "        buf[:, :, 3] = orig[:, :, 3]\n"
    "        surface.get_data()[:] = buf.tobytes()\n"
    "        surface.mark_dirty()\n"
    "\n"
    "        n_shadow    = int((shadow_gate    > 0.5).sum())\n"
    "        n_highlight = int((highlight_gate > 0.5).sum())\n"
    "        print(f\"    Paint Split Toning complete \"\n"
    "              f\"(shadow_px={n_shadow} highlight_px={n_highlight})\")\n"
)

# Anchor: last lines of paint_scumble_pass (most recently added pass)
ANCHOR = (
    "        n_bristle = int((bristle_mask > 0.5).sum())\n"
    "        n_active  = int((gate > 0.2).sum())\n"
    "        print(f\"    Paint Scumble complete \"\n"
    "              f\"(bristle_px={n_bristle} active_px={n_active})\")"
)

with open("stroke_engine.py", "r", encoding="utf-8") as f:
    content = f.read()

assert "feininger_crystalline_prism_pass" not in content, "Feininger pass already in file!"
assert "paint_split_toning_pass" not in content, "Split toning pass already in file!"
assert ANCHOR in content, "Anchor not found in stroke_engine.py!"

content = content.replace(ANCHOR, ANCHOR + FEININGER_PASS + SPLIT_TONING_PASS)

with open("stroke_engine.py", "w", encoding="utf-8") as f:
    f.write(content)

print("stroke_engine.py updated with feininger_crystalline_prism_pass and paint_split_toning_pass")

# Verify
import importlib, sys
for mod in list(sys.modules.keys()):
    if "stroke_engine" in mod:
        del sys.modules[mod]
from stroke_engine import Painter
assert hasattr(Painter, "feininger_crystalline_prism_pass"), "feininger_crystalline_prism_pass missing!"
assert hasattr(Painter, "paint_split_toning_pass"), "paint_split_toning_pass missing!"
print("Verified: both passes present in Painter")
