"""Session 237: insert rouault_stained_glass_pass + paint_scumble_pass into stroke_engine.py."""
import sys, os
sys.stdout.reconfigure(encoding='utf-8')
os.chdir(os.path.dirname(os.path.abspath(__file__)))

ROUAULT_PASS = (
    "\n"
    "    def rouault_stained_glass_pass(\n"
    "        self,\n"
    "        contour_thresh: float = 0.18,\n"
    "        contour_depth:  float = 0.72,\n"
    "        contour_power:  float = 1.8,\n"
    "        lead_cool:      float = 0.08,\n"
    "        jewel_boost:    float = 0.55,\n"
    "        opacity:        float = 0.82,\n"
    "    ) -> None:\n"
    "        r\"\"\"\n"
    "        Rouault Stained Glass -- session 237: ONE HUNDRED AND FORTY-EIGHTH distinct mode.\n"
    "\n"
    "        Implements Georges Rouault (1871-1958) Expressionist stained-glass aesthetic.\n"
    "        Three stages unified by a single Sobel gradient magnitude map:\n"
    "\n"
    "        Stage 1 CONTOUR DETECTION via Sobel derivative:\n"
    "        sx = sobel(lum, axis=1); sy = sobel(lum, axis=0);\n"
    "        grad = sqrt(sx^2 + sy^2); grad_norm = clip(grad/contour_thresh, 0, 1);\n"
    "        contour_gate = grad_norm^contour_power.\n"
    "        FIRST pass in project to use a spatial derivative (Sobel operator) as\n"
    "        its primary tool -- all prior passes use luminance thresholds, chroma\n"
    "        gates, bell-curve functions, or morphological operators.\n"
    "\n"
    "        Stage 2 CONTOUR DARKENING + LEAD-LINE COOL TINT:\n"
    "        R,G,B *= (1 - contour_depth * contour_gate).\n"
    "        Then shift boundary toward blue-grey of raw lead came:\n"
    "        R -= contour_gate * lead_cool * 0.60;\n"
    "        G -= contour_gate * lead_cool * 0.30;\n"
    "        B += contour_gate * lead_cool.\n"
    "        No prior pass darkens by gradient magnitude.\n"
    "\n"
    "        Stage 3 INTERIOR JEWEL SATURATION (inverse gradient gate):\n"
    "        interior_gate = clip(1 - grad_norm, 0, 1);\n"
    "        sat_scale = 1 + jewel_boost * interior_gate;\n"
    "        ch = lum + (ch - lum) * sat_scale.\n"
    "        INVERSE GRADIENT GATE: contour zones darkened, interior zones saturated.\n"
    "\n"
    "        NOVEL vs. existing passes:\n"
    "        (a) SOBEL GRADIENT as primary spatial operator (first derivative-based pass).\n"
    "        (b) CONTOUR DARKENING by gradient magnitude (no prior pass does this).\n"
    "        (c) INVERSE GRADIENT GATE for interior saturation (complementary dual).\n"
    "        (d) LEAD-LINE COOL TINT at contour peaks (blue-grey shift of lead came).\n"
    "\n"
    "        contour_thresh : Gradient magnitude at which contour_gate saturates.\n"
    "        contour_depth  : Maximum darkening factor in contour zones [0, 1].\n"
    "        contour_power  : Power exponent on contour gate (higher = sharper lines).\n"
    "        lead_cool      : Blue-grey cool shift at maximum contour [0, 0.12].\n"
    "        jewel_boost    : Saturation multiplier in interior zones [0, 0.8].\n"
    "        opacity        : Final composite opacity.\n"
    "        \"\"\"\n"
    "        import numpy as _np\n"
    "        from scipy.ndimage import sobel as _sobel\n"
    "\n"
    "        print(\"    Rouault Stained Glass pass (session 237 -- 148th mode)...\")\n"
    "\n"
    "        surface = self.canvas.surface\n"
    "        orig = _np.frombuffer(surface.get_data(), dtype=_np.uint8).reshape(\n"
    "            (self.canvas.h, self.canvas.w, 4)).copy()\n"
    "        h, w = orig.shape[:2]\n"
    "\n"
    "        b0 = orig[:, :, 0].astype(_np.float32) / 255.0\n"
    "        g0 = orig[:, :, 1].astype(_np.float32) / 255.0\n"
    "        r0 = orig[:, :, 2].astype(_np.float32) / 255.0\n"
    "\n"
    "        lum = (0.299 * r0 + 0.587 * g0 + 0.114 * b0).astype(_np.float32)\n"
    "\n"
    "        # Stage 1: Sobel gradient magnitude\n"
    "        sx = _sobel(lum, axis=1).astype(_np.float32)\n"
    "        sy = _sobel(lum, axis=0).astype(_np.float32)\n"
    "        grad = _np.sqrt(sx ** 2 + sy ** 2)\n"
    "        ct = float(contour_thresh)\n"
    "        grad_norm = _np.clip(grad / (ct + 1e-7), 0.0, 1.0)\n"
    "        cp = float(contour_power)\n"
    "        contour_gate = grad_norm ** cp\n"
    "\n"
    "        # Stage 2: Contour darkening + lead-line cool tint\n"
    "        cd = float(contour_depth)\n"
    "        r1 = _np.clip(r0 * (1.0 - cd * contour_gate), 0.0, 1.0)\n"
    "        g1 = _np.clip(g0 * (1.0 - cd * contour_gate), 0.0, 1.0)\n"
    "        b1 = _np.clip(b0 * (1.0 - cd * contour_gate), 0.0, 1.0)\n"
    "        lc = float(lead_cool)\n"
    "        r2 = _np.clip(r1 - contour_gate * lc * 0.60, 0.0, 1.0)\n"
    "        g2 = _np.clip(g1 - contour_gate * lc * 0.30, 0.0, 1.0)\n"
    "        b2 = _np.clip(b1 + contour_gate * lc,         0.0, 1.0)\n"
    "\n"
    "        # Stage 3: Interior jewel saturation\n"
    "        interior_gate = _np.clip(1.0 - grad_norm, 0.0, 1.0)\n"
    "        jb = float(jewel_boost)\n"
    "        lum2 = (0.299 * r2 + 0.587 * g2 + 0.114 * b2).astype(_np.float32)\n"
    "        sat_scale = 1.0 + jb * interior_gate\n"
    "        r3 = _np.clip(lum2 + (r2 - lum2) * sat_scale, 0.0, 1.0)\n"
    "        g3 = _np.clip(lum2 + (g2 - lum2) * sat_scale, 0.0, 1.0)\n"
    "        b3 = _np.clip(lum2 + (b2 - lum2) * sat_scale, 0.0, 1.0)\n"
    "\n"
    "        op = float(opacity)\n"
    "        new_r = r0 * (1.0 - op) + r3 * op\n"
    "        new_g = g0 * (1.0 - op) + g3 * op\n"
    "        new_b = b0 * (1.0 - op) + b3 * op\n"
    "\n"
    "        buf = orig.copy()\n"
    "        buf[:, :, 2] = _np.clip(new_r * 255, 0, 255).astype(_np.uint8)\n"
    "        buf[:, :, 1] = _np.clip(new_g * 255, 0, 255).astype(_np.uint8)\n"
    "        buf[:, :, 0] = _np.clip(new_b * 255, 0, 255).astype(_np.uint8)\n"
    "        buf[:, :, 3] = orig[:, :, 3]\n"
    "        surface.get_data()[:] = buf.tobytes()\n"
    "        surface.mark_dirty()\n"
    "\n"
    "        n_contour  = int((contour_gate > 0.3).sum())\n"
    "        n_interior = int((interior_gate > 0.7).sum())\n"
    "        print(f\"    Rouault Stained Glass complete \"\n"
    "              f\"(contour_px={n_contour} interior_px={n_interior})\")\n"
)

SCUMBLE_PASS = (
    "\n"
    "    def paint_scumble_pass(\n"
    "        self,\n"
    "        bristle_sigma:  float = 0.75,\n"
    "        bristle_thresh: float = 0.60,\n"
    "        scumble_lift:   float = 0.13,\n"
    "        cool_tint:      float = 0.055,\n"
    "        lum_gate_low:   float = 0.25,\n"
    "        lum_gate_high:  float = 0.85,\n"
    "        opacity:        float = 0.46,\n"
    "        seed:           int   = 237,\n"
    "    ) -> None:\n"
    "        r\"\"\"\n"
    "        Paint Scumble -- session 237 improvement.\n"
    "\n"
    "        Scumbling: a nearly-dry brush loaded with semi-opaque lighter paint is\n"
    "        dragged roughly over a darker underpainting, catching on canvas texture\n"
    "        peaks and skipping valleys, revealing the underlayer in a broken pattern.\n"
    "\n"
    "        THREE-STAGE SCUMBLE SIMULATION:\n"
    "\n"
    "        Stage 1 SPARSE BRISTLE MASK: uniform noise smoothed at bristle_sigma,\n"
    "        normalised to [0,1], then thresholded at bristle_thresh to produce a\n"
    "        near-binary sparse mask of bristle contact zones.  FIRST in project to\n"
    "        use a thresholded binary noise mask -- all prior noise passes use\n"
    "        continuous noise (film_grain, pigment_granulation).\n"
    "\n"
    "        Stage 2 LUMINANCE GATE: scumbling concentrates in mid-to-upper luminance\n"
    "        zones (shadows are too dark to lift significantly).\n"
    "        lum_gate = clip((lum - lum_gate_low)/(lum_gate_high - lum_gate_low), 0, 1).\n"
    "        combined_gate = bristle_mask * lum_gate.\n"
    "\n"
    "        Stage 3 SCUMBLE DEPOSIT: cool asymmetric channel lift in gate zones:\n"
    "        R += gate * scumble_lift * 0.82;\n"
    "        G += gate * scumble_lift * 0.92;\n"
    "        B += gate * (scumble_lift + cool_tint).\n"
    "        Models thin cool dry-paint deposit catching on texture peaks.\n"
    "\n"
    "        NOVEL vs. existing passes:\n"
    "        (a) SPARSE THRESHOLDED NOISE bristle pattern (binary vs. continuous).\n"
    "        (b) LUMINANCE-GATED POSITIVE LIFT (distinct from impasto, varnish, granulation).\n"
    "        (c) COOL ASYMMETRIC CHANNEL LIFT via sparse binary gate.\n"
    "\n"
    "        bristle_sigma  : Gaussian blur sigma for noise smoothing.\n"
    "        bristle_thresh : Threshold for binarising the noise [0.5-0.7 typical].\n"
    "        scumble_lift   : Maximum luminance lift in bristle zones [0, 0.20].\n"
    "        cool_tint      : Additional blue lift over scumble_lift [0, 0.10].\n"
    "        lum_gate_low   : Luminance below which scumbling has no effect.\n"
    "        lum_gate_high  : Luminance above which scumbling is at full effect.\n"
    "        opacity        : Final composite opacity.\n"
    "        seed           : RNG seed for reproducibility.\n"
    "        \"\"\"\n"
    "        import numpy as _np\n"
    "        from scipy.ndimage import gaussian_filter as _gf\n"
    "\n"
    "        print(\"    Paint Scumble pass (session 237 improvement)...\")\n"
    "\n"
    "        surface = self.canvas.surface\n"
    "        orig = _np.frombuffer(surface.get_data(), dtype=_np.uint8).reshape(\n"
    "            (self.canvas.h, self.canvas.w, 4)).copy()\n"
    "        h, w = orig.shape[:2]\n"
    "\n"
    "        b0 = orig[:, :, 0].astype(_np.float32) / 255.0\n"
    "        g0 = orig[:, :, 1].astype(_np.float32) / 255.0\n"
    "        r0 = orig[:, :, 2].astype(_np.float32) / 255.0\n"
    "\n"
    "        lum = (0.299 * r0 + 0.587 * g0 + 0.114 * b0).astype(_np.float32)\n"
    "\n"
    "        # Stage 1: Sparse bristle mask via thresholded noise\n"
    "        rng = _np.random.RandomState(int(seed))\n"
    "        noise = rng.uniform(0.0, 1.0, (h, w)).astype(_np.float32)\n"
    "        smoothed = _gf(noise, float(bristle_sigma))\n"
    "        sn_min = float(smoothed.min())\n"
    "        sn_max = float(smoothed.max())\n"
    "        smoothed = (smoothed - sn_min) / (sn_max - sn_min + 1e-7)\n"
    "        bristle_mask = (smoothed > float(bristle_thresh)).astype(_np.float32)\n"
    "\n"
    "        # Stage 2: Luminance gate\n"
    "        low  = float(lum_gate_low)\n"
    "        high = float(lum_gate_high)\n"
    "        lum_gate = _np.clip((lum - low) / (high - low + 1e-7), 0.0, 1.0)\n"
    "        gate = bristle_mask * lum_gate\n"
    "\n"
    "        # Stage 3: Scumble deposit (cool asymmetric channel lift)\n"
    "        sl = float(scumble_lift)\n"
    "        ct = float(cool_tint)\n"
    "        r1 = _np.clip(r0 + gate * sl * 0.82, 0.0, 1.0)\n"
    "        g1 = _np.clip(g0 + gate * sl * 0.92, 0.0, 1.0)\n"
    "        b1 = _np.clip(b0 + gate * (sl + ct), 0.0, 1.0)\n"
    "\n"
    "        op = float(opacity)\n"
    "        new_r = r0 * (1.0 - op) + r1 * op\n"
    "        new_g = g0 * (1.0 - op) + g1 * op\n"
    "        new_b = b0 * (1.0 - op) + b1 * op\n"
    "\n"
    "        buf = orig.copy()\n"
    "        buf[:, :, 2] = _np.clip(new_r * 255, 0, 255).astype(_np.uint8)\n"
    "        buf[:, :, 1] = _np.clip(new_g * 255, 0, 255).astype(_np.uint8)\n"
    "        buf[:, :, 0] = _np.clip(new_b * 255, 0, 255).astype(_np.uint8)\n"
    "        buf[:, :, 3] = orig[:, :, 3]\n"
    "        surface.get_data()[:] = buf.tobytes()\n"
    "        surface.mark_dirty()\n"
    "\n"
    "        n_bristle = int((bristle_mask > 0.5).sum())\n"
    "        n_active  = int((gate > 0.2).sum())\n"
    "        print(f\"    Paint Scumble complete \"\n"
    "              f\"(bristle_px={n_bristle} active_px={n_active})\")\n"
)

ANCHOR = (
    "        n_valley = int((valley_gate > 0.2).sum())\n"
    "        n_dark   = int((valley_gate > 0.5).sum())\n"
    "        print(f\"    Paint Medium Pooling complete \"\n"
    "              f\"(valley_px={n_valley} deep_valley_px={n_dark})\")"
)

with open("stroke_engine.py", "r", encoding="utf-8") as f:
    content = f.read()

assert "rouault_stained_glass_pass" not in content, "Rouault pass already in file!"
assert "paint_scumble_pass" not in content, "Scumble pass already in file!"
assert ANCHOR in content, "Anchor not found in stroke_engine.py!"

content = content.replace(ANCHOR, ANCHOR + ROUAULT_PASS + SCUMBLE_PASS)

with open("stroke_engine.py", "w", encoding="utf-8") as f:
    f.write(content)

print("stroke_engine.py updated with rouault_stained_glass_pass and paint_scumble_pass")

# Verify
import importlib, sys
for mod in list(sys.modules.keys()):
    if "stroke_engine" in mod:
        del sys.modules[mod]
from stroke_engine import Painter
assert hasattr(Painter, "rouault_stained_glass_pass"), "rouault_stained_glass_pass missing!"
assert hasattr(Painter, "paint_scumble_pass"), "paint_scumble_pass missing!"
print(f"Verified: both passes present in Painter")
